hoistPattern:
  - '*'
hoistedDependencies:
  '@alloc/quick-lru@5.2.0':
    '@alloc/quick-lru': private
  '@esbuild/aix-ppc64@0.24.2':
    '@esbuild/aix-ppc64': private
  '@esbuild/android-arm64@0.24.2':
    '@esbuild/android-arm64': private
  '@esbuild/android-arm@0.24.2':
    '@esbuild/android-arm': private
  '@esbuild/android-x64@0.24.2':
    '@esbuild/android-x64': private
  '@esbuild/darwin-arm64@0.24.2':
    '@esbuild/darwin-arm64': private
  '@esbuild/darwin-x64@0.24.2':
    '@esbuild/darwin-x64': private
  '@esbuild/freebsd-arm64@0.24.2':
    '@esbuild/freebsd-arm64': private
  '@esbuild/freebsd-x64@0.24.2':
    '@esbuild/freebsd-x64': private
  '@esbuild/linux-arm64@0.24.2':
    '@esbuild/linux-arm64': private
  '@esbuild/linux-arm@0.24.2':
    '@esbuild/linux-arm': private
  '@esbuild/linux-ia32@0.24.2':
    '@esbuild/linux-ia32': private
  '@esbuild/linux-loong64@0.24.2':
    '@esbuild/linux-loong64': private
  '@esbuild/linux-mips64el@0.24.2':
    '@esbuild/linux-mips64el': private
  '@esbuild/linux-ppc64@0.24.2':
    '@esbuild/linux-ppc64': private
  '@esbuild/linux-riscv64@0.24.2':
    '@esbuild/linux-riscv64': private
  '@esbuild/linux-s390x@0.24.2':
    '@esbuild/linux-s390x': private
  '@esbuild/linux-x64@0.24.2':
    '@esbuild/linux-x64': private
  '@esbuild/netbsd-arm64@0.24.2':
    '@esbuild/netbsd-arm64': private
  '@esbuild/netbsd-x64@0.24.2':
    '@esbuild/netbsd-x64': private
  '@esbuild/openbsd-arm64@0.24.2':
    '@esbuild/openbsd-arm64': private
  '@esbuild/openbsd-x64@0.24.2':
    '@esbuild/openbsd-x64': private
  '@esbuild/sunos-x64@0.24.2':
    '@esbuild/sunos-x64': private
  '@esbuild/win32-arm64@0.24.2':
    '@esbuild/win32-arm64': private
  '@esbuild/win32-ia32@0.24.2':
    '@esbuild/win32-ia32': private
  '@esbuild/win32-x64@0.24.2':
    '@esbuild/win32-x64': private
  '@kurkle/color@0.3.4':
    '@kurkle/color': private
  '@rollup/rollup-android-arm-eabi@4.34.0':
    '@rollup/rollup-android-arm-eabi': private
  '@rollup/rollup-android-arm64@4.34.0':
    '@rollup/rollup-android-arm64': private
  '@rollup/rollup-darwin-arm64@4.34.0':
    '@rollup/rollup-darwin-arm64': private
  '@rollup/rollup-darwin-x64@4.34.0':
    '@rollup/rollup-darwin-x64': private
  '@rollup/rollup-freebsd-arm64@4.34.0':
    '@rollup/rollup-freebsd-arm64': private
  '@rollup/rollup-freebsd-x64@4.34.0':
    '@rollup/rollup-freebsd-x64': private
  '@rollup/rollup-linux-arm-gnueabihf@4.34.0':
    '@rollup/rollup-linux-arm-gnueabihf': private
  '@rollup/rollup-linux-arm-musleabihf@4.34.0':
    '@rollup/rollup-linux-arm-musleabihf': private
  '@rollup/rollup-linux-arm64-gnu@4.34.0':
    '@rollup/rollup-linux-arm64-gnu': private
  '@rollup/rollup-linux-arm64-musl@4.34.0':
    '@rollup/rollup-linux-arm64-musl': private
  '@rollup/rollup-linux-loongarch64-gnu@4.34.0':
    '@rollup/rollup-linux-loongarch64-gnu': private
  '@rollup/rollup-linux-powerpc64le-gnu@4.34.0':
    '@rollup/rollup-linux-powerpc64le-gnu': private
  '@rollup/rollup-linux-riscv64-gnu@4.34.0':
    '@rollup/rollup-linux-riscv64-gnu': private
  '@rollup/rollup-linux-s390x-gnu@4.34.0':
    '@rollup/rollup-linux-s390x-gnu': private
  '@rollup/rollup-linux-x64-gnu@4.34.0':
    '@rollup/rollup-linux-x64-gnu': private
  '@rollup/rollup-linux-x64-musl@4.34.0':
    '@rollup/rollup-linux-x64-musl': private
  '@rollup/rollup-win32-arm64-msvc@4.34.0':
    '@rollup/rollup-win32-arm64-msvc': private
  '@rollup/rollup-win32-ia32-msvc@4.34.0':
    '@rollup/rollup-win32-ia32-msvc': private
  '@rollup/rollup-win32-x64-msvc@4.34.0':
    '@rollup/rollup-win32-x64-msvc': private
  '@tailwindcss/node@4.0.3':
    '@tailwindcss/node': private
  '@tailwindcss/oxide-android-arm64@4.0.3':
    '@tailwindcss/oxide-android-arm64': private
  '@tailwindcss/oxide-darwin-arm64@4.0.3':
    '@tailwindcss/oxide-darwin-arm64': private
  '@tailwindcss/oxide-darwin-x64@4.0.3':
    '@tailwindcss/oxide-darwin-x64': private
  '@tailwindcss/oxide-freebsd-x64@4.0.3':
    '@tailwindcss/oxide-freebsd-x64': private
  '@tailwindcss/oxide-linux-arm-gnueabihf@4.0.3':
    '@tailwindcss/oxide-linux-arm-gnueabihf': private
  '@tailwindcss/oxide-linux-arm64-gnu@4.0.3':
    '@tailwindcss/oxide-linux-arm64-gnu': private
  '@tailwindcss/oxide-linux-arm64-musl@4.0.3':
    '@tailwindcss/oxide-linux-arm64-musl': private
  '@tailwindcss/oxide-linux-x64-gnu@4.0.3':
    '@tailwindcss/oxide-linux-x64-gnu': private
  '@tailwindcss/oxide-linux-x64-musl@4.0.3':
    '@tailwindcss/oxide-linux-x64-musl': private
  '@tailwindcss/oxide-win32-arm64-msvc@4.0.3':
    '@tailwindcss/oxide-win32-arm64-msvc': private
  '@tailwindcss/oxide-win32-x64-msvc@4.0.3':
    '@tailwindcss/oxide-win32-x64-msvc': private
  '@tailwindcss/oxide@4.0.3':
    '@tailwindcss/oxide': private
  '@types/estree@1.0.6':
    '@types/estree': private
  '@vue/shared@3.5.13':
    '@vue/shared': private
  asynckit@0.4.0:
    asynckit: private
  combined-stream@1.0.8:
    combined-stream: private
  cssesc@3.0.0:
    cssesc: private
  delayed-stream@1.0.0:
    delayed-stream: private
  detect-libc@1.0.3:
    detect-libc: private
  duplexer@0.1.1:
    duplexer: private
  enhanced-resolve@5.18.0:
    enhanced-resolve: private
  focus-trap@6.9.4:
    focus-trap: private
  follow-redirects@1.15.9:
    follow-redirects: private
  form-data@4.0.1:
    form-data: private
  fsevents@2.3.3:
    fsevents: private
  graceful-fs@4.2.11:
    graceful-fs: private
  jiti@2.4.2:
    jiti: private
  lightningcss-darwin-arm64@1.29.1:
    lightningcss-darwin-arm64: private
  lightningcss-darwin-x64@1.29.1:
    lightningcss-darwin-x64: private
  lightningcss-freebsd-x64@1.29.1:
    lightningcss-freebsd-x64: private
  lightningcss-linux-arm-gnueabihf@1.29.1:
    lightningcss-linux-arm-gnueabihf: private
  lightningcss-linux-arm64-gnu@1.29.1:
    lightningcss-linux-arm64-gnu: private
  lightningcss-linux-arm64-musl@1.29.1:
    lightningcss-linux-arm64-musl: private
  lightningcss-linux-x64-gnu@1.29.1:
    lightningcss-linux-x64-gnu: private
  lightningcss-linux-x64-musl@1.29.1:
    lightningcss-linux-x64-musl: private
  lightningcss-win32-arm64-msvc@1.29.1:
    lightningcss-win32-arm64-msvc: private
  lightningcss-win32-x64-msvc@1.29.1:
    lightningcss-win32-x64-msvc: private
  lightningcss@1.29.1:
    lightningcss: private
  lodash.castarray@4.4.0:
    lodash.castarray: private
  lodash.isplainobject@4.0.6:
    lodash.isplainobject: private
  lodash.merge@4.6.2:
    lodash.merge: private
  mime-db@1.52.0:
    mime-db: private
  mime-types@2.1.35:
    mime-types: private
  mini-svg-data-uri@1.4.4:
    mini-svg-data-uri: private
  nanoid@3.3.8:
    nanoid: private
  picocolors@1.1.1:
    picocolors: private
  picomatch@2.3.1:
    picomatch: private
  postcss-selector-parser@6.0.10:
    postcss-selector-parser: private
  proxy-from-env@1.1.0:
    proxy-from-env: private
  rollup@4.34.0:
    rollup: private
  source-map-js@1.2.1:
    source-map-js: private
  tabbable@5.3.3:
    tabbable: private
  tapable@2.2.1:
    tapable: private
  util-deprecate@1.0.2:
    util-deprecate: private
  vite-plugin-full-reload@1.2.0:
    vite-plugin-full-reload: private
ignoredBuilds:
  - esbuild
included:
  dependencies: true
  devDependencies: true
  optionalDependencies: true
injectedDeps: {}
layoutVersion: 5
nodeLinker: isolated
packageManager: pnpm@10.11.0
pendingBuilds: []
prunedAt: Sat, 24 May 2025 09:29:48 GMT
publicHoistPattern: []
registries:
  '@jsr': https://npm.jsr.io/
  default: https://registry.npmjs.org/
skipped:
  - '@esbuild/aix-ppc64@0.24.2'
  - '@esbuild/android-arm64@0.24.2'
  - '@esbuild/android-arm@0.24.2'
  - '@esbuild/android-x64@0.24.2'
  - '@esbuild/darwin-arm64@0.24.2'
  - '@esbuild/darwin-x64@0.24.2'
  - '@esbuild/freebsd-arm64@0.24.2'
  - '@esbuild/freebsd-x64@0.24.2'
  - '@esbuild/linux-arm64@0.24.2'
  - '@esbuild/linux-arm@0.24.2'
  - '@esbuild/linux-ia32@0.24.2'
  - '@esbuild/linux-loong64@0.24.2'
  - '@esbuild/linux-mips64el@0.24.2'
  - '@esbuild/linux-ppc64@0.24.2'
  - '@esbuild/linux-riscv64@0.24.2'
  - '@esbuild/linux-s390x@0.24.2'
  - '@esbuild/linux-x64@0.24.2'
  - '@esbuild/netbsd-arm64@0.24.2'
  - '@esbuild/netbsd-x64@0.24.2'
  - '@esbuild/openbsd-arm64@0.24.2'
  - '@esbuild/openbsd-x64@0.24.2'
  - '@esbuild/sunos-x64@0.24.2'
  - '@esbuild/win32-arm64@0.24.2'
  - '@esbuild/win32-ia32@0.24.2'
  - '@rollup/rollup-android-arm-eabi@4.34.0'
  - '@rollup/rollup-android-arm64@4.34.0'
  - '@rollup/rollup-darwin-arm64@4.34.0'
  - '@rollup/rollup-darwin-x64@4.34.0'
  - '@rollup/rollup-freebsd-arm64@4.34.0'
  - '@rollup/rollup-freebsd-x64@4.34.0'
  - '@rollup/rollup-linux-arm-gnueabihf@4.34.0'
  - '@rollup/rollup-linux-arm-musleabihf@4.34.0'
  - '@rollup/rollup-linux-arm64-gnu@4.34.0'
  - '@rollup/rollup-linux-arm64-musl@4.34.0'
  - '@rollup/rollup-linux-loongarch64-gnu@4.34.0'
  - '@rollup/rollup-linux-powerpc64le-gnu@4.34.0'
  - '@rollup/rollup-linux-riscv64-gnu@4.34.0'
  - '@rollup/rollup-linux-s390x-gnu@4.34.0'
  - '@rollup/rollup-linux-x64-gnu@4.34.0'
  - '@rollup/rollup-linux-x64-musl@4.34.0'
  - '@rollup/rollup-win32-arm64-msvc@4.34.0'
  - '@rollup/rollup-win32-ia32-msvc@4.34.0'
  - '@tailwindcss/oxide-android-arm64@4.0.3'
  - '@tailwindcss/oxide-darwin-arm64@4.0.3'
  - '@tailwindcss/oxide-darwin-x64@4.0.3'
  - '@tailwindcss/oxide-freebsd-x64@4.0.3'
  - '@tailwindcss/oxide-linux-arm-gnueabihf@4.0.3'
  - '@tailwindcss/oxide-linux-arm64-gnu@4.0.3'
  - '@tailwindcss/oxide-linux-arm64-musl@4.0.3'
  - '@tailwindcss/oxide-linux-x64-gnu@4.0.3'
  - '@tailwindcss/oxide-linux-x64-musl@4.0.3'
  - '@tailwindcss/oxide-win32-arm64-msvc@4.0.3'
  - fsevents@2.3.3
  - lightningcss-darwin-arm64@1.29.1
  - lightningcss-darwin-x64@1.29.1
  - lightningcss-freebsd-x64@1.29.1
  - lightningcss-linux-arm-gnueabihf@1.29.1
  - lightningcss-linux-arm64-gnu@1.29.1
  - lightningcss-linux-arm64-musl@1.29.1
  - lightningcss-linux-x64-gnu@1.29.1
  - lightningcss-linux-x64-musl@1.29.1
  - lightningcss-win32-arm64-msvc@1.29.1
storeDir: C:\Users\ADVAN\AppData\Local\pnpm\store\v10
virtualStoreDir: C:\xampp\htdocs\apalagi\node_modules\.pnpm
virtualStoreDirMaxLength: 60
